### ISSUE TITLE
如果只注入C库的话，是否可以不需要java文件独立工作？

### ISSUE THREAD

**Issue by patrickkh7788** [asLody/AndHook#60]
是否可以脱离java文件独立工作的（在c里面hookjava函数是否需要 andhook.lib.AndHook）？

**Comment by patrickkh7788** [comment]
我尝试在C库里通过dlopen 加载libAK.so, 然后通过符号AKGetInvokeInterface来调用。结果抛出了下面的错误。

11-12 11:38:21.873 12414 12414 E com.fewpod.apps: dlopen ok!
11-12 11:38:21.873 12414 12414 E com.fewpod.apps: dlsym ok!
11-12 11:38:21.873 12414 12414 E com.fewpod.apps: getak = aaf120f0, f00000e0
--------- beginning of crash
11-12 11:38:21.874 12414 12414 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa000f00000e0 in tid 12414 (com.fewpod.demo)
11-12 11:38:21.874   341   341 W         : debuggerd: handling request: pid=12414 uid=10072 gid=10072 tid=12414
11-12 11:38:21.944 12431 12431 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-12 11:38:21.944 12431 12431 F DEBUG   : LineageOS Version: '14.1-20180406-UNOFFICIAL-rolex'
11-12 11:38:21.944 12431 12431 F DEBUG   : Build fingerprint: 'Xiaomi/rolex/rolex:7.1.2/N2G47H/V9.2.6.0.NCCMIEK:user/release-keys'
11-12 11:38:21.944 12431 12431 F DEBUG   : Revision: '0'
11-12 11:38:21.944 12431 12431 F DEBUG   : ABI: 'arm64'
11-12 11:38:21.944 12431 12431 F DEBUG   : pid: 12414, tid: 12414, name: com.fewpod.demo  >>> com.fewpod.demo <<<
11-12 11:38:21.944 12431 12431 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa000f00000e0
11-12 11:38:21.944 12431 12431 F DEBUG   :     x0   000000000000002c  x1   46eba90ed1631c1b  x2   0000000000000004  x3   0000000000000000
11-12 11:38:21.944 12431 12431 F DEBUG   :     x4   0000007ffb572178  x5   000000000000003f  x6   0000000000000001  x7   0000007fb51454ac
11-12 11:38:21.944 12431 12431 F DEBUG   :     x8   9100a000f00000e0  x9   46eba90ed1631c1b  x10  0000000000000000  x11  46eba90ed1631c1b
11-12 11:38:21.944 12431 12431 F DEBUG   :     x12  000000005be903bd  x13  0000000000000000  x14  0000000000000000  x15  00341466a5988d7b
11-12 11:38:21.944 12431 12431 F DEBUG   :     x16  0000007fb514da68  x17  0000007fb5cf7ebc  x18  000000000000001b  x19  0000007ffb5729f8
11-12 11:38:21.945 12431 12431 F DEBUG   :     x20  0000007fb2896a00  x21  0000007fb283e300  x22  0000007f96368f98  x23  46eba90ed1631c1b
11-12 11:38:21.945 12431 12431 F DEBUG   :     x24  0000007ffb572aac  x25  0000007fa69ac680  x26  0000007fb28e8000  x27  0000000000000029
11-12 11:38:21.945 12431 12431 F DEBUG   :     x28  0000007fb2896a00  x29  0000007ffb572830  x30  0000007f9636abdc
11-12 11:38:21.945 12431 12431 F DEBUG   :     sp   0000007ffb5726c0  pc   0000a000f00000e0  pstate 0000000060000000
11-12 11:38:21.948 12431 12431 F DEBUG   : 
11-12 11:38:21.948 12431 12431 F DEBUG   : backtrace:
11-12 11:38:21.948 12431 12431 F DEBUG   :     #00 pc 0000a000f00000e0  <unknown>
11-12 11:38:21.948 12431 12431 F DEBUG   :     #01 pc 00000000000e7bd8  /data/app/com.fewpod.demo-1/lib/arm64/libandfix.so (tryJniLoad+628)
11-12 11:38:21.948 12431 12431 F DEBUG   :     #02 pc 00000000000e606c  /data/app/com.fewpod.demo-1/lib/arm64/libandfix.so (JNI_OnLoad+212)
11-12 11:38:21.948 12431 12431 F DEBUG   :     #03 pc 00000000002f5924  /system/lib64/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectP8_jstringPS9_+2136)
11-12 11:38:21.949 12431 12431 F DEBUG   :     #04 pc 0000000000004698  /system/lib64/libopenjdkjvm.so (JVM_NativeLoad+284)
11-12 11:38:21.949 12431 12431 F DEBUG   :     #05 pc 0000000073681ac0  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x29b2000)
11-12 11:38:22.112  1510 12432 W ActivityManager:   Force finishing activity com.fewpod.demo/.MainActivity
11-12 11:38:22.120  1510  1532 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
11-12 11:38:22.121   341   341 W         : debuggerd: resuming target 12414
11-12 11:38:22.131  1510 10458 I ActivityManager: Process com.fewpod.demo (pid 12414) has died
11-12 11:38:22.131  1510 10458 D ActivityManager: cleanUpApplicationRecord -- 12414
11-12 11:38:22.134  1510 10458 E SchedPolicy: add_tid_to_cgroup failed; fd=-1
11-12 11:38:22.134  1510 10458 W ActivityManager: Failed setting process group of 10147 to 2
11-12 11:38:22.134  1510 10458 W System.err: java.lang.IllegalArgumentException: Invalid argument: 10147
11-12 11:38:22.134  1510 10458 W System.err: 	at android.os.Process.setProcessGroup(Native Method)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20704)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21307)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2472)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2137)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1838)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1828)
11-12 11:38:22.134  1510 10458 W System.err: 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:5282)
11-12 11:38:22.135  1510 10458 W System.err: 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:5423)
11-12 11:38:22.135  1510 10458 W System.err: 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1496)
11-12 11:38:22.135  1510 10458 W System.err: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
11-12 11:38:22.137   529   529 I Zygote  : Process 12414 exited due to signal (11)
11-12 11:38:22.145  1510  6295 D WindowManager: relayoutVisibleWindow: Window{a4f6174 u0 com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
11-12 11:38:22.165  1510  6295 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@f74982 attribute=android.view.inputmethod.EditorInfo@e3c1893, token = android.os.BinderProxy@1129547
11-12 11:38:22.175  1510  6295 E QCOM PowerHAL: Failed to acquire lock.
11-12 11:38:22.195  1510  8247 I OpenGLRenderer: Initialized EGL, version 1.4
11-12 11:38:22.195  1510  8247 D OpenGLRenderer: Swap behavior 1
11-12 11:38:23.186  1754  1754 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
11-12 11:38:23.201  1754  1754 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=9 sndbuf=212992 outq=0 send_len=48
11-12 11:38:23.375  1510  1537 D LuxLevels: bright hysteresis constant= 0.1, threshold=153.83017, lux=139.84561
11-12 11:38:23.375  1510  1537 D LuxLevels: dark hysteresis constant= 0.2, threshold=111.87649, lux=139.84561
